spring:
  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: 3600s # 1 hora

  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: "yyyy-MM-dd 'T'HH:mm:ss.SSS'Z'"
    time-zone: UTC

  cache:
    cache-names: laboratorio,laboratorioPages,laboratorioRemedios
    caffeine:
      spec: maximumSize=500,expireAfterWrite=300s

logging:
  level:
    root: INFO
