CREATE TABLE laboratorio (
    id BINARY(16) NOT NULL PRIMARY KEY,

    nome VARCHAR(100) NOT NULL,
    endereco VARCHAR(200),
    telefone VARCHAR(20),
    email VARCHAR(100),

	createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE KEY uq_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE remedio (
    id BINARY(16) NOT NULL PRIMARY KEY,

    nome VARCHAR(100) NOT NULL,
    via VARCHAR(30) NOT NULL,
    lote VARCHAR(50),
    quantidade INT NOT NULL,
    validade DATE,
    laboratorio_id BINARY(16) NOT NULL,
	
	createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (laboratorio_id) REFERENCES laboratorio(id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
