CREATE TABLE usuario (
    id BINARY(16) NOT NULL PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(60) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    dataNascimento VARCHAR(20) NOT NULL,
    telefone VARCHAR(20),
    cep VARCHAR(20),
    endereco VARCHAR(255),
    complemento VARCHAR(255),
    cidade VARCHAR(100),
    uf VARCHAR(2),
    isAdmin BOOLEAN NOT NULL,

    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
